import { readFileSync, writeFileSync } from 'node:fs';
import { dirname, join } from 'node:path';
import { fileURLToPath } from 'node:url';
import { describe, it } from 'vitest';
import { canonicalizeForSign } from './crypto.js';

// Generator (not an assertion): emits server-rs/tests/vectors/ts-vectors.json —
// the JCS canonical bytes produced by the *production* auth-proof signer (the
// `canonicalize` npm package, via canonicalizeForSign), for the same battery the
// Go emitter defines in server/interop_vectors_test.go. The Rust spike then
// checks serde_jcs against both Go and these TS bytes (ADR-0018, phase 1).
//
// Reads the inputs from go-vectors.json so the battery stays single-sourced.
// Gated behind GEN_VECTORS so it never runs in `make test`.
//
// Regenerate (after the Go emitter has produced go-vectors.json):
//   cd web && GEN_VECTORS=1 pnpm exec vitest run --project=unit src/lib/jcs-interop-vectors.gen.test.ts

const vectorsDir = join(
    dirname(fileURLToPath(import.meta.url)),
    '../../../server-rs/tests/vectors',
);

const hex = (b: Uint8Array) => Buffer.from(b).toString('hex');

describe('JCS interop vectors (TS production signer)', () => {
    it.skipIf(!process.env.GEN_VECTORS)('emits ts-vectors.json', () => {
        const go = JSON.parse(
            readFileSync(join(vectorsDir, 'go-vectors.json'), 'utf8'),
        );

        const jcs_battery = (
            go.jcs_battery as { name: string; input_json: string }[]
        ).map((c) => ({
            name: c.name,
            canonical_hex: hex(canonicalizeForSign(JSON.parse(c.input_json))),
        }));

        const auth_proof_payload_canonical_hex = hex(
            canonicalizeForSign(JSON.parse(go.auth_proof.payload_json)),
        );

        const out = {
            _note:
                'Generated by web/src/lib/jcs-interop-vectors.gen.test.ts (GEN_VECTORS=1) ' +
                'with the canonicalize npm package — the production auth-proof signer. ' +
                'Do not hand-edit. See tasks/rust-backend-spike.md.',
            jcs_battery,
            auth_proof_payload_canonical_hex,
        };

        writeFileSync(
            join(vectorsDir, 'ts-vectors.json'),
            `${JSON.stringify(out, null, 2)}\n`,
        );
    });
});
