package main

import (
	"crypto/ed25519"
	"encoding/hex"
	"encoding/json"
	"os"
	"path/filepath"
	"testing"

	"github.com/gowebpki/jcs"
)

// Golden vectors for the Rust port spike (ADR-0018, tasks/rust-backend-spike.md).
//
// This is a generator, not an assertion: it writes server-rs/tests/vectors/go-vectors.json,
// which the Rust side (server-rs/tests/interop.rs) consumes to prove byte-identity with Go.
// Gated behind GEN_VECTORS so it never runs in `make test`. All inputs are fixed
// (secret, ed25519 seed, timestamp) so committed output is stable across runs.
//
// Regenerate (from the server/ module root):
//
//	cd server && GEN_VECTORS=1 go test -run TestGenerateInteropVectors

type interopVectors struct {
	Note       string          `json:"_note"`
	Tokens     []tokenVector   `json:"tokens"`
	AuthProof  authProofVector `json:"auth_proof"`
	JCSBattery []jcsCase       `json:"jcs_battery"`
}

type tokenVector struct {
	Secret     string `json:"secret"`
	UserID     string `json:"user_id"`
	DeviceID   string `json:"device_id"`
	KeyVersion int    `json:"key_version"`
	Token      string `json:"token"`
}

type authProofVector struct {
	PublicKeyHex    string `json:"public_key_hex"`
	PayloadJSON     string `json:"payload_json"`
	SignatureB64URL string `json:"signature_b64url"`
	JCSCanonicalHex string `json:"jcs_canonical_hex"`
}

type jcsCase struct {
	Name         string `json:"name"`
	InputJSON    string `json:"input_json"`
	CanonicalHex string `json:"canonical_hex"`
}

func TestGenerateInteropVectors(t *testing.T) {
	if os.Getenv("GEN_VECTORS") == "" {
		t.Skip("set GEN_VECTORS=1 to regenerate server-rs interop vectors")
	}

	v := interopVectors{
		Note: "Generated by server/interop_vectors_test.go (GEN_VECTORS=1). Golden fixtures for the Rust spike — do not hand-edit. See tasks/rust-backend-spike.md.",
	}

	// --- Tokens (kv >= 1; the clamp case is covered by token.rs unit tests) ---
	for _, tv := range []tokenVector{
		{Secret: "test-server-secret", UserID: "u-alice", DeviceID: "d-1", KeyVersion: 3},
		{Secret: "test-server-secret", UserID: "u-bob", DeviceID: "d-xyz", KeyVersion: 1},
		{Secret: "another-secret", UserID: "u-carol", DeviceID: "d-2", KeyVersion: 7},
	} {
		tv.Token = generateToken([]byte(tv.Secret), tv.UserID, tv.DeviceID, tv.KeyVersion)
		v.Tokens = append(v.Tokens, tv)
	}

	// --- Auth proof: payload signed over its JCS-canonical bytes (mirrors signAuthProofKV) ---
	seed := make([]byte, ed25519.SeedSize)
	for i := range seed {
		seed[i] = byte(i + 1) // fixed, deterministic key
	}
	priv := ed25519.NewKeyFromSeed(seed)
	pub := priv.Public().(ed25519.PublicKey)

	payload := map[string]any{
		"user_id":     "u-alice",
		"device_id":   "d-1",
		"timestamp":   "2026-01-01T00:00:00Z",
		"key_version": 2,
	}
	raw, err := json.Marshal(payload)
	if err != nil {
		t.Fatal(err)
	}
	canonical, err := jcs.Transform(raw)
	if err != nil {
		t.Fatal(err)
	}
	sig := ed25519.Sign(priv, canonical)
	v.AuthProof = authProofVector{
		PublicKeyHex:    hex.EncodeToString(pub),
		PayloadJSON:     string(raw),
		SignatureB64URL: b64url.EncodeToString(sig),
		JCSCanonicalHex: hex.EncodeToString(canonical),
	}

	// --- JCS battery: Rust serde_jcs must reproduce these canonical bytes exactly ---
	//
	// The test only checks Rust == Go. A case where both agree but both deviate
	// from the ECMAScript reference would still pass here and only surface at the
	// TS cross-check step — keep that in mind when reading "pass 2" results.
	battery := []struct{ name, input string }{
		// Baseline.
		{"key_ordering", `{"c":3,"a":1,"b":2}`},
		{"nested", `{"z":{"b":2,"a":1},"a":[3,2,1]}`},
		{"unicode", `{"text":"café — naïve","quote":"a\"b","backslash":"a\\b"}`},
		{"auth_proof_shape", `{"user_id":"u-alice","device_id":"d-1","timestamp":"2026-01-01T00:00:00Z","key_version":2}`},
		{"absent_key_version", `{"user_id":"u-alice","device_id":"d-1","timestamp":"2026-01-01T00:00:00Z"}`},
		{"numbers_tame", `{"int":42,"neg":-7,"float":3.5,"zero":0,"big":1000000000000}`},

		// Pass 1 — broader UTF-8 + escaping. Expected to match Go: raw UTF-8 out,
		// only the mandatory escapes. The 4-byte case is the one that matters for
		// the later TS cross-check, since JS strings are UTF-16 (surrogate pairs).
		{"cyrillic", `{"text":"Здравей, свят"}`},
		{"kanji", `{"text":"日本語のテスト 漢字"}`},
		{"emoji_4byte", `{"text":"grin 😀 clef 𝄞 astral"}`},
		{"control_escapes", `{"b":"x\by","t":"x\ty","n":"x\ny","f":"x\fy","r":"x\ry"}`},
		{"forward_slash", `{"plain":"a/b/c","escaped":"a\/b"}`},

		// Pass 2 — number stress / finding-hunt. These MAY diverge (Rust != Go);
		// a failure is a finding to fold into the protocol docs, not a regression.
		{"num_over_2pow53", `{"n":10000000000000001}`},
		{"num_exp_large", `{"n":1e21}`},
		{"num_exp_small", `{"n":1e-7}`},
		{"num_neg_zero", `{"n":-0}`},
		{"num_trailing_zeros", `{"a":1.0,"b":1.50,"c":100.0}`},
	}
	for _, c := range battery {
		canon, err := jcs.Transform([]byte(c.input))
		if err != nil {
			t.Fatalf("jcs %s: %v", c.name, err)
		}
		v.JCSBattery = append(v.JCSBattery, jcsCase{Name: c.name, InputJSON: c.input, CanonicalHex: hex.EncodeToString(canon)})
	}

	out, err := json.MarshalIndent(v, "", "  ")
	if err != nil {
		t.Fatal(err)
	}
	dir := filepath.Join("..", "server-rs", "tests", "vectors")
	if err := os.MkdirAll(dir, 0o755); err != nil {
		t.Fatal(err)
	}
	path := filepath.Join(dir, "go-vectors.json")
	if err := os.WriteFile(path, out, 0o644); err != nil {
		t.Fatal(err)
	}
	t.Logf("wrote %s (%d bytes)", path, len(out))
}
